format_version: v1.0
type: UniqueComponent
attributes: {id: le_gfx_lcdc}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: CanvasModeOnly}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: DisplayHeight}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_lcdc, value: '480'}
  - type: Menu
    attributes: {id: DisplaySettingsMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: DisplayWidth}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_lcdc, value: '800'}
  - type: Comment
    attributes: {id: HALComment}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: OutputColorMode}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Boolean
    attributes: {id: Overlay1LayerEnable}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: Overlay2LayerEnable}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: TotalNumLayers}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_lcdc, value: '1'}
  - type: Boolean
    attributes: {id: UseGPU}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: Graphics Display}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_disp_pdatm5000_800x480}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_display}
  - type: DirectDependency
    attributes: {id: LCDC}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: lcdc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: LCDC_LCDC}
  - type: DirectCapability
    attributes: {id: le_gfx_driver_lcdc}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_canvas}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_display_driver}
- type: ElementPosition
  attributes: {x: '416', y: '247', id: le_gfx_lcdc}
