name: GitHub Traffic Stats Tracker

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once daily at midnight UTC
  workflow_dispatch:

jobs:
  update-traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Traffic Data
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GITHUB_TOKEN }}
          path: traffic-data.json

      - name: Commit and Push Results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add traffic-data.json
          git commit -m "Updated daily traffic data"
          git push
